# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.4
_src_path: https://github.com/jupyterlab/extension-template
author_email: ''
author_name: Datalayer
has_binder: true
has_settings: false
kind: server
labextension_name: jupyter-server-nbmodel
project_short_description: A Jupyter Server extension to execute code cell from the
    server.
python_name: jupyter_server_nbmodel
repository: https://github.com/datalayer/jupyter-server-nbmodel
test: true

